// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDw2H8iiW5o4qUOISLOKXuKGGckd2u3VdA',
    appId: '1:488425280849:web:6572b81b9ff7bf379e2f70',
    messagingSenderId: '488425280849',
    projectId: 'learning-65b2a',
    authDomain: 'learning-65b2a.firebaseapp.com',
    storageBucket: 'learning-65b2a.appspot.com',
    measurementId: 'G-1SX03BGHWX',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBEY50BO75hhQjTAgk5McByo4OGNZgxcMc',
    appId: '1:488425280849:android:42a8a737431697c49e2f70',
    messagingSenderId: '488425280849',
    projectId: 'learning-65b2a',
    storageBucket: 'learning-65b2a.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAxt0TLpFzA4M06k_xqbEF6c73KLF6JCLM',
    appId: '1:488425280849:ios:f7bea548e3ef93f69e2f70',
    messagingSenderId: '488425280849',
    projectId: 'learning-65b2a',
    storageBucket: 'learning-65b2a.appspot.com',
    iosBundleId: 'com.example.myFoodApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAxt0TLpFzA4M06k_xqbEF6c73KLF6JCLM',
    appId: '1:488425280849:ios:c2f6cff309bf98129e2f70',
    messagingSenderId: '488425280849',
    projectId: 'learning-65b2a',
    storageBucket: 'learning-65b2a.appspot.com',
    iosBundleId: 'com.example.myFoodApp.RunnerTests',
  );
}
